"""Serving the panel mock, and filling it with the game's own cases.

The browser refuses module imports from file:// URLs, so this is a small HTTP
server rooted at the mod being worked on, with the mock page mounted beside it.
Nothing here knows anything about a particular panel: the page takes the
renderer's path as a query parameter and calls one exported function per
fixture.
"""

from __future__ import annotations

import functools
import http.server
import json
import socketserver
import webbrowser
from pathlib import Path
from urllib.parse import urlencode

from . import logs

PAGE = Path(__file__).resolve().parents[1] / "mock"


class _Handler(http.server.SimpleHTTPRequestHandler):
    """Serves the mod directory, with /_civ7lab/ mapped to the mock page."""

    def translate_path(self, path):
        if path.startswith("/_civ7lab/"):
            return str(PAGE / path[len("/_civ7lab/"):].split("?", 1)[0])
        return super().translate_path(path)

    def log_message(self, *args):
        pass


def _field(data, path: str):
    """A dotted path into a record's data: "loc.x" is data["loc"]["x"]. Missing is None."""
    for step in path.split("."):
        if not isinstance(data, dict):
            return None
        data = data.get(step)
    return data


def latest_by(found: list, fields: list[str]) -> list:
    """One entry per distinct value of `fields`, the last one seen.

    A panel that prints itself every time it opens prints the same case again
    each time it is hovered. The last reading is the current one; each case
    keeps the place it first appeared in, so the order still follows play.
    """
    kept: dict = {}
    for data in found:
        key = json.dumps([_field(data, path) for path in fields], sort_keys=True, default=str)
        kept[key] = data        # an existing key keeps its place in a dict
    return list(kept.values())


def fixtures_from_records(kind: str = "fixture", log: Path | None = None,
                          out: Path | None = None,
                          latest: list[str] | None = None) -> tuple[Path, int, int]:
    """Harvest the panels the game actually drew into a fixtures module.

    A panel that prints what it drew as a record of this kind gives the mock
    real cases: the farm, the wonder, the coastal tile, exactly as they were on
    the map. Invented fixtures agree with whatever the renderer already does.

    `latest` names the fields that identify a case (dotted paths into the data,
    e.g. ["cityName", "loc.x", "loc.y"]); only the last record of each is kept.
    Nothing here knows what a case is, which is why the caller says.

    Returns the path written, the records found, and the fixtures kept.
    """
    report = logs.read_records(log)
    found = [record.data for record in report.records if record.kind == kind]
    total = len(found)
    if latest:
        found = latest_by(found, latest)
    out = Path(out) if out else Path.cwd() / "fixtures.js"
    out.write_text(
        "// GENERATED by civ7lab mock fixtures. Do not edit by hand.\n"
        "// Each entry is one panel the game really drew, harvested from UI.log.\n"
        f"export const FIXTURES = {json.dumps(found, indent=1, ensure_ascii=False)};\n")
    return out, total, len(found)


def serve(root: Path, renderer: str, export: str = "render", fixtures: str = "fixtures.js",
          port: int = 8000, open_browser: bool = False) -> str:
    root = Path(root).resolve()
    query = urlencode({"renderer": f"/{renderer}", "export": export,
                       "fixtures": f"/{fixtures}"})
    url = f"http://localhost:{port}/_civ7lab/panel.html?{query}"
    handler = functools.partial(_Handler, directory=str(root))
    socketserver.TCPServer.allow_reuse_address = True
    with socketserver.TCPServer(("127.0.0.1", port), handler) as server:
        print(f"serving {root} at {url}\nCtrl-C to stop")
        if open_browser:
            webbrowser.open(url)
        try:
            server.serve_forever()
        except KeyboardInterrupt:
            print("\nstopped")
    return url
